syntax = "proto3";

package blockchain;

option go_package = "github.com/caio/btc-indexer/gen/blockchain";

service BlockchainService {
  rpc GetBlockByHeight(GetBlockByHeightRequest) returns (GetBlockResponse);
  rpc GetTransaction(GetTransactionRequest) returns (GetTransactionResponse);
}

message GetBlockByHeightRequest {
  int64 height = 1;
}

message GetBlockResponse {
  string hash = 1;
  int64 height = 2;
}

message GetTransactionRequest {
  string txid = 1;
}

message GetTransactionResponse {
  string txid = 1;
  string block_hash = 2;
  int64 block_height = 3;
}
